spring.datasource.url=jdbc:postgresql://localhost:5432/hospital_db
spring.datasource.username=postgres
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=8080

jwt.secret=VGhpc0lzQVN0cm9uZ0RlbW9TZWNyZXRLZXlGb3JKV1QxMjM0NTY3ODkw
jwt.expiration.ms=86400000