spring.datasource.url=jdbc:postgresql://dpg-d7nofhmgvqtc73b0gfi0-a.singapore-postgres.render.com:5432/hospital_z2o8
spring.datasource.username=hospital_z2o8_user
spring.datasource.password=92Esv8VuLO2LvKP0RjBAVC6cI8zIsOXC

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080

jwt.secret=VGhpc0lzQVN0cm9uZ0RlbW9TZWNyZXRLZXlGb3JKV1QxMjM0NTY3ODkw
jwt.expiration.ms=86400000